services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: eshop
      POSTGRES_PASSWORD: eshop
      POSTGRES_DB: catalog
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eshop -d catalog"]
      interval: 5s
      retries: 5

  redis:
    image: redis:7.4-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass secret
    volumes:
      - cache_data:/data

  catalog-service:
    build:
      context: .
      dockerfile: bins/catalog-service/Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://eshop:eshop@postgres:5432/catalog
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  cache_data:
    driver: local
