apiVersion: v1
kind: Service
metadata:
  name: kafka           # services reach Kafka at "kafka:9092"
  namespace: e-shop
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
