apiVersion: v1
kind: Service
metadata:
  name: postgres        # other Pods reach Postgres at "postgres:5432"
  namespace: e-shop
spec:
  selector:
    app: postgres       # route traffic to Pods with this label
  ports:
    - port: 5432
      targetPort: 5432
